#!/usr/bin/env python3
"""Generate databricks/hr_pipeline_notebook.sql and optionally the Lakeview dashboard JSON from sql/02-05.
Usage: python scripts/build_databricks.py [--with-dashboard]"""
import json, pathlib, sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
CATALOG, SCHEMA, VOLUME = "workspace", "da_learn_02", "/Volumes/workspace/da_learn_02/raw"
FILES = {"stg_employee": "emp_attrition.csv"}
SEP = "\n\n-- COMMAND ----------\n\n"


def md(text):
    return "\n".join(["-- MAGIC %md"] + [f"-- MAGIC {l}".rstrip() for l in text.strip().splitlines()])


def statements(path):
    out, buf = [], []
    for line in path.read_text().splitlines():
        buf.append(line)
        code = line.split("--")[0] if ("--" in line and line[:line.find("--")].count("'") % 2 == 0) else line
        if code.rstrip().endswith(";"):
            keep = [l for l in buf if not l.strip().startswith("--")]
            head = next((l for l in buf if l.strip().startswith("--")), None)
            out.append("\n".join(([head] if head else []) + keep).strip()); buf = []
    return out


VIZ = [
    ("Attrition by department", "Bar: X = department_name, Y = attrition_pct",
     "SELECT department_name, employees, leavers, attrition_pct, avg_monthly_income FROM a_attrition_by_department ORDER BY attrition_pct DESC"),
    ("Attrition by job role", "Horizontal bar: Y = job_role, X = attrition_pct",
     "SELECT job_role, job_level, employees, leavers, attrition_pct FROM a_attrition_by_job_role ORDER BY attrition_pct DESC"),
    ("Overtime vs attrition", "Bar: X = overtime_status, Y = attrition_pct",
     "SELECT overtime_status, employees, leavers, attrition_pct FROM a_overtime_attrition"),
    ("Tenure vs attrition", "Bar: X = tenure_band, Y = attrition_pct",
     "SELECT tenure_band, employees, leavers, attrition_pct FROM a_tenure_attrition ORDER BY tenure_band"),
    ("Job satisfaction vs attrition", "Bar: X = job_satisfaction_label, Y = attrition_pct",
     "SELECT job_satisfaction, job_satisfaction_label, employees, attrition_pct FROM a_satisfaction_attrition ORDER BY job_satisfaction"),
    ("Travel vs attrition", "Bar: X = business_travel, Y = attrition_pct",
     "SELECT business_travel, employees, leavers, attrition_pct FROM a_travel_attrition"),
]


def notebook():
    cells = ["-- Databricks notebook source\n" + md(f"""
# HR employee attrition analysis - SQL pipeline (Databricks SQL)
**Status: executed on Databricks** (serverless SQL warehouse). Generated by `scripts/build_databricks.py` from `sql/`.

1. Upload `emp_attrition.csv` to the Unity Catalog volume `{VOLUME}` (see `databricks/SETUP.md`).
2. Attach to a SQL warehouse or a DBR 13.3+ cluster and *Run all*.
3. Cells: config -> staging (`read_files`) -> 02 cleaning -> 03 star schema -> 04 KPIs -> 05 data-quality -> visualization queries.""")]
    cells.append(f"-- Config: change catalog / schema here (and in the dashboard JSON) if needed\nCREATE SCHEMA IF NOT EXISTS {CATALOG}.{SCHEMA};\nUSE CATALOG {CATALOG};\nUSE SCHEMA {SCHEMA};")
    cells.append(md("## 01 Staging - all columns as STRING (`inferColumnTypes => false`), casting happens in 02"))
    for t, f in FILES.items():
        cells.append(f"CREATE OR REPLACE TABLE {t} AS\nSELECT *\nFROM read_files('{VOLUME}/{f}',\n  format => 'csv', header => true, multiLine => true, escape => '\"', inferColumnTypes => false);")
    titles = {"02_cleaning.sql": "02 Cleaning", "03_model.sql": "03 Star schema", "04_analysis.sql": "04 Business KPIs",
              "05_quality_checks.sql": "05 Data-quality checks"}
    for f, title in titles.items():
        cells.append(md(f"## {title} (`sql/{f}`)"))
        cells += statements(ROOT / "sql" / f)
    cells.append(md("## Quality summary\nAll assertions should be PASS."))
    cells.append("SELECT * FROM dq_row_counts ORDER BY entity;")
    cells.append("SELECT * FROM dq_assertions ORDER BY status, check_name;")
    cells.append(md("## Visualizations\nRun each cell, click **+ > Visualization** under the result and configure as described. The same views are pre-built in `hr_attrition_dashboard.lvdash.json`."))
    cells.append("SELECT * FROM a_kpi_headline;")
    for title, how, q in VIZ:
        cells.append(f"-- Visualization: {title}\n-- {how}\n{q};")
    return SEP.join(cells) + "\n"


def ds(name, display, sql):
    return {"name": name, "displayName": display, "queryLines": [sql]}


def field(n, expr=None):
    return {"name": n, "expression": expr or f"`{n}`"}


def widget(name, ds_name, fields, spec, pos):
    return {"widget": {"name": name, "queries": [{"name": "main_query", "query": {"datasetName": ds_name, "fields": fields, "disaggregated": True}}], "spec": spec}, "position": pos}


def counter(name, col, title, fmt, x, y=1):
    enc = {"fieldName": col, "displayName": title}
    if fmt: enc["format"] = fmt
    return widget(name, "kpi", [field(col)], {"version": 2, "widgetType": "counter", "encodings": {"value": enc}, "frame": {"showTitle": True, "title": title}}, {"x": x, "y": y, "width": 1, "height": 2})


def chart(name, kind, ds_name, x, y, title, pos, xs="categorical", ys="quantitative", horizontal=False):
    xe = {"fieldName": x[0], "displayName": x[1], "scale": {"type": xs}}
    ye = {"fieldName": y[0], "displayName": y[1], "scale": {"type": ys}}
    enc = {"x": ye, "y": xe} if horizontal else {"x": xe, "y": ye}
    return widget(name, ds_name, [field(x[0]), field(y[0])], {"version": 3, "widgetType": kind, "encodings": enc, "frame": {"showTitle": True, "title": title}}, pos)


def dashboard():
    q = lambda t: f"{CATALOG}.{SCHEMA}.{t}"
    pct = {"type": "number-percent", "decimalPlaces": {"type": "max", "places": 2}}
    num = {"type": "number", "abbreviation": "compact", "decimalPlaces": {"type": "max", "places": 0}}
    usd = {"type": "number-currency", "currencyCode": "USD", "abbreviation": "compact", "decimalPlaces": {"type": "max", "places": 0}}
    datasets = [
        ds("kpi", "Headline KPIs",
           f"SELECT employees_total, leavers, attrition_pct / 100 AS attrition_rate, avg_monthly_income, "
           f"attrition_pct_overtime / 100 AS ot_attrition_rate, attrition_pct_no_overtime / 100 AS no_ot_attrition_rate "
           f"FROM {q('a_kpi_headline')}"),
        ds("dept", "By department", f"SELECT department_name, employees, leavers, attrition_pct FROM {q('a_attrition_by_department')}"),
        ds("role", "By job role", f"SELECT job_role, employees, attrition_pct FROM {q('a_attrition_by_job_role')}"),
        ds("ot", "Overtime", f"SELECT overtime_status, employees, attrition_pct FROM {q('a_overtime_attrition')}"),
        ds("tenure", "Tenure", f"SELECT tenure_band, employees, attrition_pct FROM {q('a_tenure_attrition')} ORDER BY tenure_band"),
        ds("satis", "Satisfaction", f"SELECT job_satisfaction_label, employees, attrition_pct FROM {q('a_satisfaction_attrition')} ORDER BY job_satisfaction"),
        ds("travel", "Travel", f"SELECT business_travel, employees, attrition_pct FROM {q('a_travel_attrition')}"),
    ]
    p1 = [{"widget": {"name": "title", "multilineTextboxSpec": {"lines": ["## IBM HR employee attrition - executive overview (full data)"]}}, "position": {"x": 0, "y": 0, "width": 6, "height": 1}},
          counter("kpi_emp", "employees_total", "Employees", num, 0),
          counter("kpi_attr", "attrition_rate", "Attrition rate", pct, 1),
          counter("kpi_ot", "ot_attrition_rate", "OT attrition", pct, 2),
          counter("kpi_income", "avg_monthly_income", "Avg monthly income", usd, 3),
          {"widget": {"name": "kpi_note", "multilineTextboxSpec": {"lines": ["Attrition = Attrition Yes. Source: IBM HR Analytics (Kaggle), ODbL + DbCL. Star schema in workspace.da_learn_02."]}}, "position": {"x": 4, "y": 1, "width": 2, "height": 2}},
          chart("dept_bar", "bar", "dept", ("department_name", "Department"), ("attrition_pct", "Attrition %"), "Attrition by department", {"x": 0, "y": 3, "width": 3, "height": 6}),
          chart("role_bar", "bar", "role", ("job_role", "Job role"), ("attrition_pct", "Attrition %"), "Attrition by job role", {"x": 3, "y": 3, "width": 3, "height": 6}, horizontal=True)]
    p2 = [{"widget": {"name": "title2", "multilineTextboxSpec": {"lines": ["## Drivers: overtime, tenure, satisfaction, travel"]}}, "position": {"x": 0, "y": 0, "width": 6, "height": 1}},
          chart("ot_bar", "bar", "ot", ("overtime_status", "Overtime"), ("attrition_pct", "Attrition %"), "Overtime vs attrition", {"x": 0, "y": 1, "width": 3, "height": 5}),
          chart("tenure_bar", "bar", "tenure", ("tenure_band", "Tenure band"), ("attrition_pct", "Attrition %"), "Tenure vs attrition", {"x": 3, "y": 1, "width": 3, "height": 5}),
          chart("satis_bar", "bar", "satis", ("job_satisfaction_label", "Job satisfaction"), ("attrition_pct", "Attrition %"), "Job satisfaction vs attrition", {"x": 0, "y": 6, "width": 3, "height": 5}),
          chart("travel_bar", "bar", "travel", ("business_travel", "Travel"), ("attrition_pct", "Attrition %"), "Business travel vs attrition", {"x": 3, "y": 6, "width": 3, "height": 5})]
    return {"datasets": datasets, "pages": [
        {"name": "overview", "displayName": "Executive overview", "pageType": "PAGE_TYPE_CANVAS", "layout": p1},
        {"name": "drivers", "displayName": "Attrition drivers", "pageType": "PAGE_TYPE_CANVAS", "layout": p2}]}


if __name__ == "__main__":
    out = ROOT / "databricks"; out.mkdir(exist_ok=True)
    (out / "hr_pipeline_notebook.sql").write_text(notebook())
    if "--with-dashboard" in sys.argv:
        (out / "hr_attrition_dashboard.lvdash.json").write_text(json.dumps(dashboard(), separators=(",", ":")) + "\n")
    print("wrote", sorted(p.name for p in out.iterdir()))
